name: Build Notion SDK

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      # 2
      - name: 2. Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      # 3
      - name: 3. Grant execute permission for Gradle
        run: chmod +x gradlew

      # 4.
#      - name: 4. Code style check (Spotless)
#        run: ./gradlew spotlessCheck

      # 5
      - name: 5. Build with Gradle
        env:
          TESTING_BOT_TOKEN: ${{ secrets.TESTING_BOT_TOKEN }}
        run: ./gradlew build

      # 6
      - name: Coverage
        if: always()
        run: ./gradlew jacocoTestReport jacocoIntegrationTestReport

      - name: Prepare Pages content
        if: always()
        run: |
          mkdir -p pages/jacoco/unit
          mkdir -p pages/jacoco/integration

          cp -r build/reports/tests/test/* pages/jacoco/unit/
          cp -r build/reports/tests/integrationTest/* pages/jacoco/integration/

      - name: Publish to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: pages